apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: back
  name: back
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: back
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        app: back
        io.kompose.network/myapp: "true"
        io.kompose.service: back
    spec:
      containers:
      - image: ainura888docker/quotes-back:v1
        name: api
        env:
        - name: SQLALCHEMY_DATABASE_URI 
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: SQLALCHEMY_DATABASE_URI
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
